name: Build and publish Docker image

on:
  release:
    types: [published]
    
jobs:
  build_and_push:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rubenernst/restic-node
          tag_with_ref: true
